// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright (C) 2026 David Lin <dtwlin@gmail.com>

//! Diff view component rendering commit metadata, diffstat, and unified hunks.

use std::io::Write;
use tigrs_core::ansi::truncate_display_width;
use tigrs_core::error::Result;
use tigrs_git::{CommitDiff, DiffHunk, FileDiff, ObjectId, StatusItem, StatusSection};

pub use crate::diff::document::{DiffDocument, DiffLineType, HunkLocation};
use crate::options::ViewOptions;
use crate::term_cap::TerminalCapabilities;
use crate::view::ViewportCursor;

/// A pre-formatted display line in the diff view.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DiffViewLine {
    /// Classification for syntax coloring.
    pub kind: DiffLineType,
    /// Raw textual content without newline.
    pub text: String,
    /// Character ranges within `text` that differ from the paired line on the
    /// other side of the change, used to emphasise intra-line (word-level)
    /// edits.
    pub emphasis: Vec<(u32, u32)>,
}

/// Full-screen scrollable diff view displaying commit metadata and patch.
#[derive(Debug, Clone)]
pub struct DiffView {
    /// Underlying commit diff data (`Arc`-shared across cache, worker, and UI to avoid deep clones).
    diff: std::sync::Arc<CommitDiff>,
    /// Fully structured diff document with parallel index tables.
    pub(crate) document: std::sync::Arc<DiffDocument>,
    /// Lazy fallback unified document when in `SideBySide` mode and terminal width drops below `side_by_side_min_width`.
    unified_fallback_document: std::sync::OnceLock<DiffDocument>,
    /// Highlighted line and vertical scroll viewport.
    nav: ViewportCursor,
    /// Horizontal column scroll offset.
    col_offset: usize,
    /// Associated status item if this diff view was opened from the status view.
    status_item: Option<StatusItem>,
    /// Whether the document was generated by an external diff formatter.
    is_external_formatter: bool,
    /// Set of 0-based file indices that are currently folded/collapsed (`za`, `zM`, `zR`).
    pub folded_files: std::collections::BTreeSet<usize>,
    /// Per-hunk extra context line overrides keyed by `(file_idx, hunk_idx)` (`+`/`=`/`_`).
    pub hunk_extra_context: std::collections::BTreeMap<(usize, usize), usize>,
    /// Whether the on-demand File Details popover (`i`) is currently open.
    pub show_file_details: bool,
}

impl DiffView {
    /// Creates a new `DiffView` by converting a `CommitDiff` into display lines using default options.
    pub fn new(diff: impl Into<std::sync::Arc<CommitDiff>>) -> Self {
        Self::new_with_options(diff, &ViewOptions::default(), None)
    }

    /// Creates a `DiffView` with an empty placeholder `DiffDocument` for standalone CLI startup,
    /// deferring document construction to [`crate::AppState::refresh_diff_view`] so the diff is
    /// built and syntax-highlighted only once using the user's loaded [`ViewOptions`].
    #[must_use]
    pub fn new_deferred(diff: impl Into<std::sync::Arc<CommitDiff>>) -> Self {
        Self::from_arc_and_document(
            diff.into(),
            std::sync::Arc::new(DiffDocument::default()),
            None,
            false,
        )
    }

    /// Creates a new `DiffView` for a working-tree status item using default options.
    pub fn new_status(diff: impl Into<std::sync::Arc<CommitDiff>>, item: StatusItem) -> Self {
        Self::new_status_with_options(diff, item, &ViewOptions::default(), None)
    }

    /// Creates a new `DiffView` with explicit options and optional blob provider for context expansion.
    pub fn new_with_options(
        diff: impl Into<std::sync::Arc<CommitDiff>>,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
    ) -> Self {
        Self::new_internal(diff.into(), None, options, None, blob_provider)
    }

    /// Creates a new `DiffView` for a status item with explicit options and blob provider.
    pub fn new_status_with_options(
        diff: impl Into<std::sync::Arc<CommitDiff>>,
        item: StatusItem,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
    ) -> Self {
        Self::new_internal(diff.into(), Some(item), options, None, blob_provider)
    }

    /// Constructs a `DiffView` directly from an `Arc<CommitDiff>` and a precomputed `Arc<DiffDocument>`.
    #[must_use]
    pub fn from_arc_and_document(
        diff: std::sync::Arc<CommitDiff>,
        document: std::sync::Arc<DiffDocument>,
        status_item: Option<StatusItem>,
        is_external_formatter: bool,
    ) -> Self {
        let folded_files =
            crate::diff::layout::default_folded_files(&diff, &ViewOptions::default());
        Self {
            diff,
            document,
            unified_fallback_document: std::sync::OnceLock::new(),
            nav: ViewportCursor::new(),
            col_offset: 0,
            status_item,
            is_external_formatter,
            folded_files,
            hunk_extra_context: std::collections::BTreeMap::new(),
            show_file_details: false,
        }
    }

    /// Returns true if any per-file folds or per-hunk context expansions are active.
    #[inline]
    #[must_use]
    pub fn has_custom_fold_or_hunk_state(&self) -> bool {
        !self.folded_files.is_empty() || !self.hunk_extra_context.is_empty()
    }

    /// Returns a reference to the shared `Arc<CommitDiff>`.
    #[inline]
    #[must_use]
    pub fn diff_arc(&self) -> &std::sync::Arc<CommitDiff> {
        &self.diff
    }

    /// Returns a reference to the shared `Arc<DiffDocument>`.
    #[inline]
    #[must_use]
    pub fn document_arc(&self) -> &std::sync::Arc<DiffDocument> {
        &self.document
    }

    /// Creates a new `DiffView` with explicit terminal capabilities and cooperative cancellation.
    pub fn new_cancellable_with_caps(
        diff: impl Into<std::sync::Arc<CommitDiff>>,
        status_item: Option<StatusItem>,
        options: &ViewOptions,
        caps: Option<&TerminalCapabilities>,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        cancel: &tigrs_core::CancellationToken,
    ) -> Option<Self> {
        if cancel.is_cancelled() {
            return None;
        }
        let diff = diff.into();
        let detected_caps;
        let active_caps = if let Some(c) = caps {
            c
        } else {
            detected_caps = TerminalCapabilities::detect();
            &detected_caps
        };
        if !options.diff_formatter.trim().is_empty()
            && let Ok(document) = crate::diff::formatter::run_external_formatter(
                &diff,
                &options.diff_formatter,
                80,
                active_caps,
            )
        {
            return Some(Self {
                diff,
                document: std::sync::Arc::new(document),
                unified_fallback_document: std::sync::OnceLock::new(),
                nav: ViewportCursor::new(),
                col_offset: 0,
                status_item,
                is_external_formatter: true,
                folded_files: std::collections::BTreeSet::new(),
                hunk_extra_context: std::collections::BTreeMap::new(),
                show_file_details: false,
            });
        }
        let folded_files = crate::diff::layout::default_folded_files(&diff, options);
        let empty_hunk_ctx = std::collections::BTreeMap::new();
        let document = crate::diff::layout::build_diff_document_cancellable_with_state(
            &diff,
            options,
            active_caps,
            blob_provider,
            &folded_files,
            &empty_hunk_ctx,
            Some(cancel),
        )?;
        Some(Self {
            diff,
            document: std::sync::Arc::new(document),
            unified_fallback_document: std::sync::OnceLock::new(),
            nav: ViewportCursor::new(),
            col_offset: 0,
            status_item,
            is_external_formatter: false,
            folded_files,
            hunk_extra_context: std::collections::BTreeMap::new(),
            show_file_details: false,
        })
    }

    pub(crate) fn build_documents(
        diff: &CommitDiff,
        options: &ViewOptions,
        caps: &TerminalCapabilities,
        blob_provider: Option<crate::diff::BlobLineProvider>,
    ) -> (DiffDocument, bool) {
        let default_folds = crate::diff::layout::default_folded_files(diff, options);
        let empty_hunk_ctx = std::collections::BTreeMap::new();
        Self::build_documents_with_state(
            diff,
            options,
            caps,
            blob_provider,
            &default_folds,
            &empty_hunk_ctx,
        )
    }

    pub(crate) fn build_documents_with_state(
        diff: &CommitDiff,
        options: &ViewOptions,
        caps: &TerminalCapabilities,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        folded_files: &std::collections::BTreeSet<usize>,
        hunk_extra_context: &std::collections::BTreeMap<(usize, usize), usize>,
    ) -> (DiffDocument, bool) {
        if !options.read_only
            && !options.diff_formatter.trim().is_empty()
            && let Ok(doc) = crate::diff::formatter::run_external_formatter(
                diff,
                &options.diff_formatter,
                80,
                caps,
            )
        {
            return (doc, true);
        }
        let doc = crate::diff::layout::build_diff_document_with_state(
            diff,
            options,
            caps,
            blob_provider,
            folded_files,
            hunk_extra_context,
        );
        (doc, false)
    }

    fn new_internal(
        diff: std::sync::Arc<CommitDiff>,
        status_item: Option<StatusItem>,
        options: &ViewOptions,
        caps: Option<&TerminalCapabilities>,
        blob_provider: Option<crate::diff::BlobLineProvider>,
    ) -> Self {
        let detected_caps;
        let active_caps = if let Some(c) = caps {
            c
        } else {
            detected_caps = TerminalCapabilities::detect();
            &detected_caps
        };
        let folded_files = crate::diff::layout::default_folded_files(&diff, options);
        let empty_hunk_ctx = std::collections::BTreeMap::new();
        let (document, is_external_formatter) = Self::build_documents_with_state(
            &diff,
            options,
            active_caps,
            blob_provider,
            &folded_files,
            &empty_hunk_ctx,
        );

        Self {
            diff,
            document: std::sync::Arc::new(document),
            unified_fallback_document: std::sync::OnceLock::new(),
            nav: ViewportCursor::new(),
            col_offset: 0,
            status_item,
            is_external_formatter,
            folded_files,
            hunk_extra_context: std::collections::BTreeMap::new(),
            show_file_details: false,
        }
    }

    /// Replaces the current `DiffDocument` with a prebuilt `new_document`, preserving
    /// semantic cursor anchoring and relative viewport offset in `O(1)` without re-layout.
    pub fn refresh_with_document(
        &mut self,
        new_document: std::sync::Arc<DiffDocument>,
        is_external_formatter: bool,
    ) {
        let screen_delta = self.nav.cursor.saturating_sub(self.nav.scroll_offset);
        let new_cursor = self.document.map_cursor_to(self.nav.cursor, &new_document);
        self.document = new_document;
        self.unified_fallback_document = std::sync::OnceLock::new();
        self.is_external_formatter = is_external_formatter;

        if self.document.is_empty() {
            self.nav.cursor = 0;
            self.nav.scroll_offset = 0;
        } else {
            self.nav.cursor = new_cursor.min(self.document.len().saturating_sub(1));
            self.nav.scroll_offset = self.nav.cursor.saturating_sub(screen_delta);
        }
    }

    /// Refreshes the diff document with updated options and optional blob provider,
    /// preserving the semantic cursor anchor, fold state, and per-hunk context state.
    pub fn refresh(
        &mut self,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
    ) {
        let caps = TerminalCapabilities::detect();
        let (new_document, is_external_formatter) = Self::build_documents_with_state(
            &self.diff,
            options,
            &caps,
            blob_provider,
            &self.folded_files,
            &self.hunk_extra_context,
        );
        self.refresh_with_document(std::sync::Arc::new(new_document), is_external_formatter);
    }

    /// Returns the number of currently folded file sections in this diff view.
    #[must_use]
    pub fn folded_file_count(&self) -> usize {
        self.folded_files.len()
    }

    /// Toggles the fold/collapse state of the file at the current cursor row (`za`).
    pub fn toggle_fold_current_file(
        &mut self,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> Option<String> {
        let f_idx = self
            .document
            .line_to_file
            .get(self.nav.cursor)
            .copied()
            .flatten()? as usize;
        let path = self.diff.files.get(f_idx)?.path.clone();
        let now_folded = if self.folded_files.contains(&f_idx) {
            self.folded_files.remove(&f_idx);
            false
        } else {
            self.folded_files.insert(f_idx);
            true
        };
        self.refresh(options, blob_provider);
        if let Some(&header_row) = self.document.file_indices.get(f_idx) {
            // If we just folded the file while cursor was inside its body, snap cursor to its header
            if now_folded || self.nav.cursor >= self.document.len() {
                self.nav.cursor = header_row.min(self.document.len().saturating_sub(1));
                self.adjust_scroll(visible_height);
            }
        }
        Some(if now_folded {
            format!("Folded {path} (za or Enter to unfold)")
        } else {
            format!("Unfolded {path}")
        })
    }

    /// Folds/collapses all files in the diff view (`zM` / `:fold-all`).
    pub fn fold_all_files(
        &mut self,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> String {
        let cur_f = self
            .document
            .line_to_file
            .get(self.nav.cursor)
            .copied()
            .flatten()
            .map(|i| i as usize);
        self.folded_files = (0..self.diff.files.len()).collect();
        self.refresh(options, blob_provider);
        if let Some(f_idx) = cur_f
            && let Some(&header_row) = self.document.file_indices.get(f_idx)
        {
            self.nav.cursor = header_row.min(self.document.len().saturating_sub(1));
            self.adjust_scroll(visible_height);
        }
        format!(
            "Folded all {} files (zR to unfold all)",
            self.diff.files.len()
        )
    }

    /// Unfolds/expands all files in the diff view (`zR` / `:unfold-all`).
    pub fn unfold_all_files(
        &mut self,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> String {
        self.folded_files.clear();
        self.refresh(options, blob_provider);
        self.adjust_scroll(visible_height);
        format!("Unfolded all {} files", self.diff.files.len())
    }

    /// Expands context lines around the hunk under the cursor by `step` lines (`+` / `=`).
    pub fn expand_current_hunk_context(
        &mut self,
        step: usize,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> Option<String> {
        let loc = self.document.selected_hunk(self.nav.cursor)?;
        let entry = self
            .hunk_extra_context
            .entry((loc.file_idx, loc.hunk_idx))
            .or_insert(0);
        *entry = entry.saturating_add(step);
        let new_extra = *entry;
        let file_path = self
            .diff
            .files
            .get(loc.file_idx)
            .map_or("", |f| f.path.as_str())
            .to_string();
        self.refresh(options, blob_provider);
        self.adjust_scroll(visible_height);
        Some(format!(
            "Expanded hunk #{} in {file_path} (+{new_extra} extra context lines)",
            loc.hunk_idx + 1
        ))
    }

    /// Shrinks extra context lines around the hunk under the cursor by `step` lines (`_`).
    pub fn shrink_current_hunk_context(
        &mut self,
        step: usize,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> Option<String> {
        let loc = self.document.selected_hunk(self.nav.cursor)?;
        let key = (loc.file_idx, loc.hunk_idx);
        let cur_extra = self.hunk_extra_context.get(&key).copied().unwrap_or(0);
        if cur_extra == 0 {
            return Some("Hunk is already at default context level".to_string());
        }
        let next_extra = cur_extra.saturating_sub(step);
        if next_extra == 0 {
            self.hunk_extra_context.remove(&key);
        } else {
            self.hunk_extra_context.insert(key, next_extra);
        }
        let file_path = self
            .diff
            .files
            .get(loc.file_idx)
            .map_or("", |f| f.path.as_str())
            .to_string();
        self.refresh(options, blob_provider);
        self.adjust_scroll(visible_height);
        Some(if next_extra == 0 {
            format!(
                "Reset hunk #{} context to default in {file_path}",
                loc.hunk_idx + 1
            )
        } else {
            format!(
                "Shrank hunk #{} in {file_path} (+{next_extra} extra context lines)",
                loc.hunk_idx + 1
            )
        })
    }

    /// Handles pressing `Enter` in the diff view:
    /// - On a diffstat file line (`DiffLineType::StatFile`), jumps directly to that file's diff header (unfolding if folded).
    /// - On a file header line (`FileHeader`, `FileOld`, `FileNew`, `ModeChange`, or file `Delimiter`), toggles folding for that file.
    /// - On a hunk header line (`DiffLineType::HunkHeader`), expands context around that hunk by `+10` lines.
    pub fn handle_enter(
        &mut self,
        options: &ViewOptions,
        blob_provider: Option<crate::diff::BlobLineProvider>,
        visible_height: usize,
    ) -> Option<String> {
        let row = self.document.rows.get(self.nav.cursor)?;
        match row.row_type {
            DiffLineType::StatFile => {
                let f_idx = self
                    .document
                    .line_to_file
                    .get(self.nav.cursor)
                    .copied()
                    .flatten()? as usize;
                let path = self.diff.files.get(f_idx)?.path.clone();
                if self.folded_files.remove(&f_idx) {
                    self.refresh(options, blob_provider);
                }
                if let Some(&target_row) = self.document.file_indices.get(f_idx) {
                    self.nav.cursor = target_row.min(self.document.len().saturating_sub(1));
                    self.adjust_scroll(visible_height);
                    return Some(format!("Jumped to {path}"));
                }
                None
            }
            DiffLineType::FileHeader
            | DiffLineType::FileOld
            | DiffLineType::FileNew
            | DiffLineType::ModeChange
            | DiffLineType::Delimiter => {
                if self
                    .document
                    .line_to_file
                    .get(self.nav.cursor)
                    .copied()
                    .flatten()
                    .is_some()
                {
                    self.toggle_fold_current_file(options, blob_provider, visible_height)
                } else {
                    None
                }
            }
            DiffLineType::HunkHeader => {
                self.expand_current_hunk_context(10, options, blob_provider, visible_height)
            }
            _ => None,
        }
    }

    /// Returns the associated status item, if any.
    pub fn status_item(&self) -> Option<&StatusItem> {
        self.status_item.as_ref()
    }

    /// Returns the selected file diff and hunk under cursor, if cursor is within a hunk.
    pub fn selected_hunk(&self) -> Option<(&FileDiff, &DiffHunk)> {
        let loc = self.document.selected_hunk(self.nav.cursor)?;
        let file = self.diff.files.get(loc.file_idx)?;
        let hunk = file.hunks.get(loc.hunk_idx)?;
        Some((file, hunk))
    }

    /// Returns all line indices within the hunk under cursor (both old and new lines on a paired side-by-side row).
    pub fn selected_lines(&self) -> Option<(&FileDiff, &DiffHunk, Vec<usize>)> {
        let (file_idx, hunk_idx, line_indices) = self.document.selected_lines(self.nav.cursor)?;
        let file = self.diff.files.get(file_idx)?;
        let hunk = file.hunks.get(hunk_idx)?;
        Some((file, hunk, line_indices))
    }

    /// Returns the selected file diff, hunk, and 0-based line index within the hunk,
    /// if cursor is on an addition, deletion, or context line.
    pub fn selected_line(&self) -> Option<(&FileDiff, &DiffHunk, usize)> {
        let loc = self.document.selected_line(self.nav.cursor)?;
        let line_idx = loc.line_idx?;
        let file = self.diff.files.get(loc.file_idx)?;
        let hunk = file.hunks.get(loc.hunk_idx)?;
        Some((file, hunk, line_idx))
    }

    /// Sets the cursor position directly, clamping to valid line range.
    pub fn set_cursor(&mut self, cursor: usize, visible_height: usize) {
        if !self.document.is_empty() {
            self.nav.cursor = cursor.min(self.document.len().saturating_sub(1));
            self.adjust_scroll(visible_height);
        }
    }

    /// Returns the commit ID being displayed.
    pub fn commit_id(&self) -> ObjectId {
        self.diff.commit_id
    }

    /// Returns the title of the diff being displayed.
    #[inline]
    #[must_use]
    pub fn title(&self) -> &str {
        &self.diff.title
    }

    /// Returns the total number of lines in the diff view.
    #[inline]
    pub fn line_count(&self) -> usize {
        self.document.len()
    }

    /// Returns the raw text of the line at index `idx`.
    #[inline]
    pub fn line_text(&self, idx: usize) -> Option<&str> {
        self.document.row_search_text(idx)
    }

    /// Returns the current cursor index (0-based).
    #[inline]
    pub fn cursor_index(&self) -> usize {
        self.nav.cursor
    }

    /// Returns the file path currently relevant at the cursor position, if any.
    pub fn current_file(&self) -> Option<&str> {
        self.document
            .line_to_file
            .get(self.nav.cursor)
            .copied()
            .flatten()
            .and_then(|idx| self.diff.files.get(idx as usize))
            .map(|f| f.path.as_str())
    }

    /// Returns the `FileDiff` currently relevant at the cursor position, if any.
    #[must_use]
    pub fn current_file_diff(&self) -> Option<&FileDiff> {
        self.document
            .line_to_file
            .get(self.nav.cursor)
            .copied()
            .flatten()
            .and_then(|idx| self.diff.files.get(idx as usize))
    }

    /// Moves the selection cursor down by `n` lines, updating the scroll viewport.
    pub fn move_down(&mut self, n: usize, visible_height: usize) {
        let total = self.document.len();
        self.nav.move_down_by(n, total, visible_height);
    }

    /// Moves the selection cursor up by `n` lines, updating the scroll viewport.
    pub fn move_up(&mut self, n: usize, visible_height: usize) {
        self.nav.move_up_by(n, visible_height);
    }

    /// Moves the cursor down by one screen page.
    pub fn page_down(&mut self, visible_height: usize) {
        let step = visible_height.saturating_sub(2).max(1);
        self.move_down(step, visible_height);
    }

    /// Moves the cursor up by one screen page.
    pub fn page_up(&mut self, visible_height: usize) {
        let step = visible_height.saturating_sub(2).max(1);
        self.move_up(step, visible_height);
    }

    /// Jumps directly to the top of the diff (line 0).
    pub fn home(&mut self) {
        self.nav.scroll_top();
    }

    /// Jumps directly to the bottom of the diff.
    pub fn end(&mut self, visible_height: usize) {
        let total = self.document.len();
        self.nav.scroll_bottom(total, visible_height);
    }

    /// Jumps to the next diff hunk header after the cursor.
    pub fn next_hunk(&mut self, visible_height: usize) {
        let next = self.document.find_next_hunk(self.nav.cursor);
        if next != self.nav.cursor {
            self.nav.cursor = next;
            self.adjust_scroll(visible_height);
        }
    }

    /// Jumps to the previous diff hunk header before the cursor.
    pub fn prev_hunk(&mut self, visible_height: usize) {
        let prev = self.document.find_prev_hunk(self.nav.cursor);
        if prev != self.nav.cursor {
            self.nav.cursor = prev;
            self.adjust_scroll(visible_height);
        }
    }

    /// Jumps to the next file diff header after the cursor.
    pub fn next_file(&mut self, visible_height: usize) {
        let next = self.document.find_next_file(self.nav.cursor);
        if next != self.nav.cursor {
            self.nav.cursor = next;
            self.adjust_scroll(visible_height);
        }
    }

    /// Jumps to the previous file diff header before the cursor.
    pub fn prev_file(&mut self, visible_height: usize) {
        let prev = self.document.find_prev_file(self.nav.cursor);
        if prev != self.nav.cursor {
            self.nav.cursor = prev;
            self.adjust_scroll(visible_height);
        }
    }

    /// Returns the current vertical scroll offset.
    #[inline]
    #[must_use]
    pub fn scroll_offset(&self) -> usize {
        self.nav.scroll_offset
    }

    /// Scrolls the viewport down by `n` lines, clamping to available lines
    /// and keeping the cursor within the visible viewport.
    pub fn scroll_line_down(&mut self, n: usize, visible_height: usize) {
        let total = self.document.len();
        self.nav.scroll_line_down(n, total, visible_height);
    }

    /// Scrolls the viewport up by `n` lines, clamping to 0
    /// and keeping the cursor within the visible viewport.
    pub fn scroll_line_up(&mut self, n: usize, visible_height: usize) {
        self.nav.scroll_line_up(n, visible_height);
    }

    /// Returns the current horizontal column scroll offset.
    #[inline]
    #[must_use]
    pub fn col_offset(&self) -> usize {
        self.col_offset
    }

    /// Scrolls left by `n` columns.
    pub fn scroll_left(&mut self, n: usize) {
        self.col_offset = self.col_offset.saturating_sub(n);
    }

    /// Scrolls right by `n` columns.
    pub fn scroll_right(&mut self, n: usize) {
        self.col_offset = self.col_offset.saturating_add(n);
    }

    /// Resets horizontal scrolling to column 0.
    pub fn scroll_first_col(&mut self) {
        self.col_offset = 0;
    }

    /// Returns a reference to the underlying structured document.
    #[inline]
    pub fn document(&self) -> &DiffDocument {
        &self.document
    }

    /// Returns a reference to the underlying commit diff.
    #[inline]
    pub fn diff(&self) -> &CommitDiff {
        &self.diff
    }

    /// Returns whether the document is generated by an external formatter.
    #[inline]
    pub fn is_external_formatter(&self) -> bool {
        self.is_external_formatter
    }

    /// Ensures the cursor remains visible within the viewport.
    fn adjust_scroll(&mut self, visible_height: usize) {
        self.nav.adjust_scroll(visible_height);
    }

    /// Returns the 0-based index of the file at or above the current cursor position.
    #[must_use]
    pub fn current_file_index(&self) -> Option<usize> {
        self.document
            .line_to_file
            .get(self.nav.cursor)
            .copied()
            .flatten()
            .map(|idx| idx as usize)
    }

    /// Returns whether the on-demand File Details popover (`i`) is currently open.
    #[inline]
    #[must_use]
    pub const fn is_showing_file_details(&self) -> bool {
        self.show_file_details
    }

    /// Toggles the on-demand File Details popover (`i`).
    pub fn toggle_file_details(&mut self) {
        self.show_file_details = !self.show_file_details;
    }

    /// Closes the File Details popover if open, returning `true` if it was open.
    pub fn close_file_details(&mut self) -> bool {
        if self.show_file_details {
            self.show_file_details = false;
            true
        } else {
            false
        }
    }

    /// Returns the text to copy (`y`) at the current cursor row.
    ///
    /// On a `FileHeader` (including single-line banners) or when the File Details popover is open,
    /// always returns the canonical `diff --git` multi-line header block.
    /// On a `HunkHeader` (including human-readable separators), always returns the canonical
    /// `@@ -old,len +new,len @@ func` header.
    #[must_use]
    pub fn yank_text_at_cursor(&self) -> Option<String> {
        if self.show_file_details {
            let f_idx = self.current_file_index().unwrap_or(0);
            return self
                .diff
                .files
                .get(f_idx)
                .map(crate::diff::layout::format_real_file_header);
        }
        let row = self.document.rows.get(self.nav.cursor)?;
        match row.row_type {
            DiffLineType::FileHeader | DiffLineType::Delimiter | DiffLineType::ModeChange => {
                let f_idx = self.current_file_index()?;
                self.diff
                    .files
                    .get(f_idx)
                    .map(crate::diff::layout::format_real_file_header)
            }
            DiffLineType::HunkHeader => {
                let loc = self
                    .document
                    .line_to_hunk
                    .get(self.nav.cursor)
                    .copied()
                    .flatten()
                    .or(row.anchor)?;
                self.diff
                    .files
                    .get(loc.file_idx)
                    .and_then(|f| f.hunks.get(loc.hunk_idx))
                    .map(crate::diff::layout::format_real_hunk_header)
            }
            _ => row
                .left
                .as_ref()
                .or(row.right.as_ref())
                .map(|c| c.text.to_string()),
        }
    }

    /// Renders the complete diff view to the terminal using default options.
    pub fn render<W: Write>(&self, writer: &mut W, width: u16, height: u16) -> Result<()> {
        self.render_with_options(writer, width, height, &ViewOptions::default())
    }

    /// Renders the complete diff view to the terminal with options and capabilities.
    #[allow(clippy::too_many_lines)]
    pub fn render_with_capabilities<W: Write>(
        &self,
        writer: &mut W,
        width: u16,
        height: u16,
        options: &ViewOptions,
        caps: &TerminalCapabilities,
    ) -> Result<()> {
        if width == 0 || height == 0 {
            return Ok(());
        }

        let w = width as usize;
        let ascii = options.line_graphics == crate::options::LineGraphics::Ascii;

        // 1. Title bar (Row 1) with File X of Y breadcrumb (P6)
        let short_id = {
            let hex = self.diff.commit_id.to_hex().to_string();
            hex[..7.min(hex.len())].to_string()
        };
        let ext_indicator = if self.is_external_formatter {
            " [ext]"
        } else {
            ""
        };
        let breadcrumb = if !self.diff.files.is_empty()
            && let Some(f_idx) = self.current_file_index()
        {
            let sep = if ascii { "--" } else { "—" };
            format!(" {} File {} of {}", sep, f_idx + 1, self.diff.files.len())
        } else {
            String::new()
        };
        let title_raw = format!(
            "[diff]{} {}{} - {}",
            ext_indicator, short_id, breadcrumb, self.diff.title
        );
        let title_line = truncate_display_width(&title_raw, w);
        let title_padded = tigrs_core::ansi::pad_display_width(title_line, w);
        write!(writer, "\x1b[1;1H\x1b[7m\x1b[1m{title_padded}\x1b[0m")?;

        // 2. Viewport body (Rows 2 .. height - 1)
        let theme = crate::diff::theme::DiffTheme::from_options(options, caps);

        let is_narrow_fallback = options.diff_layout == crate::options::DiffLayout::SideBySide
            && w < options.side_by_side_min_width as usize;

        if is_narrow_fallback && !self.is_external_formatter {
            let fallback_doc = self.unified_fallback_document.get_or_init(|| {
                let mut unified_opts = options.clone();
                unified_opts.diff_layout = crate::options::DiffLayout::Unified;
                crate::diff::layout::build_diff_document(&self.diff, &unified_opts, caps, None)
            });
            let mapped_cursor = self.document.map_cursor_to(self.nav.cursor, fallback_doc);
            let screen_delta = self.nav.cursor.saturating_sub(self.nav.scroll_offset);
            let mapped_scroll = mapped_cursor.saturating_sub(screen_delta);
            let viewport = crate::diff::paint::DiffViewport {
                width,
                height,
                scroll_offset: mapped_scroll,
                col_offset: self.col_offset,
                cursor: mapped_cursor,
            };
            crate::diff::paint::paint_diff(writer, fallback_doc, &theme, options, &viewport)?;
        } else {
            let viewport = crate::diff::paint::DiffViewport {
                width,
                height,
                scroll_offset: self.nav.scroll_offset,
                col_offset: self.col_offset,
                cursor: self.nav.cursor,
            };
            crate::diff::paint::paint_diff(writer, &self.document, &theme, options, &viewport)?;
        }

        // 2b. Adaptive Sticky File & Function Header (P2)
        // Only draws on row 2 when:
        // - diff_sticky_header is enabled
        // - visible_height >= 10 (never crowds compact splits)
        // - cursor > scroll_offset (never occludes the active cursor row at top of screen)
        // - scroll_offset > file_header_row (the file banner itself has scrolled off-screen)
        let visible_height = (height as usize).saturating_sub(2);
        if options.diff_sticky_header
            && visible_height >= 10
            && self.nav.cursor > self.nav.scroll_offset
            && let Some(f_idx_u32) = self
                .document
                .line_to_file
                .get(self.nav.scroll_offset)
                .copied()
                .flatten()
        {
            let f_idx = f_idx_u32 as usize;
            if let Some(&file_header_row) = self.document.file_indices.get(f_idx)
                && self.nav.scroll_offset > file_header_row
                && let Some(file) = self.diff.files.get(f_idx)
            {
                let status_chip = match &file.status {
                    tigrs_git::FileChangeStatus::Modified => "M",
                    tigrs_git::FileChangeStatus::Added => "A",
                    tigrs_git::FileChangeStatus::Deleted => "D",
                    tigrs_git::FileChangeStatus::Renamed { .. } => "R",
                    tigrs_git::FileChangeStatus::Copied { .. } => "C",
                    tigrs_git::FileChangeStatus::TypeChanged => "T",
                };
                let lang = crate::diff::layout::detect_file_language_badge(&file.path);
                let active_sym = self
                    .document
                    .line_to_hunk
                    .get(self.nav.scroll_offset)
                    .copied()
                    .flatten()
                    .and_then(|loc| file.hunks.get(loc.hunk_idx))
                    .and_then(|h| h.func_context.as_deref())
                    .map(crate::diff::layout::format_enclosing_symbol)
                    .filter(|s| !s.is_empty());
                let sym_part = match (lang, active_sym) {
                    (Some(l), Some(s)) => {
                        if ascii {
                            format!("  |  {l} > {s}")
                        } else {
                            format!("  ┃  {l} ▸ {s}")
                        }
                    }
                    (None, Some(s)) => {
                        if ascii {
                            format!("  |  > {s}")
                        } else {
                            format!("  ┃  ▸ {s}")
                        }
                    }
                    (Some(l), None) => {
                        if ascii {
                            format!("  |  {l}")
                        } else {
                            format!("  ┃  {l}")
                        }
                    }
                    (None, None) => String::new(),
                };
                let pin = if ascii { "[pinned]" } else { "📌" };
                let sticky_raw = format!(
                    "{pin} {}/{}  {status_chip}  {}{sym_part}   +{} -{}",
                    f_idx + 1,
                    self.diff.files.len(),
                    file.path,
                    file.additions,
                    file.deletions
                );
                let sticky_trunc = truncate_display_width(&sticky_raw, w);
                let sticky_padded = tigrs_core::ansi::pad_display_width(sticky_trunc, w);
                write!(writer, "\x1b[2;1H\x1b[2K\x1b[7m{sticky_padded}\x1b[0m")?;
            }
        }

        // 2c. On-Demand File Details Popover (`i` key, P5)
        if self.show_file_details
            && visible_height >= 6
            && let Some(file) = self
                .current_file_index()
                .and_then(|i| self.diff.files.get(i))
                .or_else(|| self.diff.files.first())
        {
            Self::render_file_details_popover(writer, w, visible_height, file, ascii)?;
        }

        // 3. Status bar (Row height)
        let total = self.document.len();
        let current = if total == 0 { 0 } else { self.nav.cursor + 1 };
        let pct = (current * 100).checked_div(total).unwrap_or(100);
        let file_ctx = self.current_file().unwrap_or("");
        let mut status_left = if let Some(item) = &self.status_item {
            let action_hint = match item.section {
                StatusSection::Staged => "u: unstage hunk, 1: unstage line",
                StatusSection::Unstaged => "u: stage hunk, 1: stage line",
                StatusSection::Untracked | StatusSection::Unmerged => "u: stage hunk",
            };
            format!("[status-diff] line {current} of {total} ({pct}%) - {file_ctx} [{action_hint}]")
        } else if file_ctx.is_empty() {
            format!("[diff] line {current} of {total} ({pct}%)")
        } else {
            format!("[diff] line {current} of {total} ({pct}%) - {file_ctx}")
        };
        if options.wrap_lines && self.col_offset == 0 {
            status_left.push_str(" [wrap]");
        } else if self.col_offset > 0 {
            use std::fmt::Write as _;
            let _ = write!(status_left, " [col +{}]", self.col_offset);
        }
        if !self.folded_files.is_empty() {
            use std::fmt::Write as _;
            let _ = write!(
                status_left,
                " [folded: {}/{}]",
                self.folded_files.len(),
                self.diff.files.len()
            );
        }
        if is_narrow_fallback {
            use std::fmt::Write as _;
            let _ = write!(
                status_left,
                " [unified layout: width {w} < {} min]",
                options.side_by_side_min_width
            );
        }
        let status_line = truncate_display_width(&status_left, w);
        let status_padded = tigrs_core::ansi::pad_display_width(status_line, w);
        write!(writer, "\x1b[{height};1H\x1b[7m{status_padded}\x1b[0m")?;

        Ok(())
    }

    fn render_file_details_popover<W: Write>(
        writer: &mut W,
        w: usize,
        visible_height: usize,
        file: &FileDiff,
        ascii: bool,
    ) -> Result<()> {
        let card_w = w.saturating_sub(4).clamp(24, 76);
        let inner_w = card_w.saturating_sub(4);
        let start_col = (w.saturating_sub(card_w)) / 2 + 1;
        let status_desc = match &file.status {
            tigrs_git::FileChangeStatus::Modified => "Modified".to_string(),
            tigrs_git::FileChangeStatus::Added => "Added".to_string(),
            tigrs_git::FileChangeStatus::Deleted => "Deleted".to_string(),
            tigrs_git::FileChangeStatus::Renamed {
                source_path,
                similarity_pct,
            } => format!("Renamed from {source_path} ({similarity_pct}%)"),
            tigrs_git::FileChangeStatus::Copied {
                source_path,
                similarity_pct,
            } => format!("Copied from {source_path} ({similarity_pct}%)"),
            tigrs_git::FileChangeStatus::TypeChanged => "TypeChanged".to_string(),
        };
        let mode_desc = match (file.old_mode, file.new_mode) {
            (Some(o), Some(n)) if o != n => format!("mode {o:06o} -> {n:06o}"),
            (None, Some(n)) | (Some(n), None) => format!("mode {n:06o}"),
            (Some(o), Some(_)) => format!("mode {o:06o}"),
            (None, None) => "mode 100644".to_string(),
        };
        let old_sha = file.old_id.as_ref().map_or_else(
            || "0000000".to_string(),
            |id| id.to_hex().to_string()[..7].to_string(),
        );
        let new_sha = file.new_id.as_ref().map_or_else(
            || "0000000".to_string(),
            |id| id.to_hex().to_string()[..7].to_string(),
        );
        let lang = crate::diff::layout::detect_file_language_badge(&file.path).unwrap_or("Text");
        let body_lines = [
            format!("Path:      {}", file.path),
            format!("Status:    {status_desc} ({mode_desc})"),
            format!("Blobs:     index {old_sha}..{new_sha}"),
            format!("Header:    diff --git a/{} b/{}", file.path, file.path),
            format!(
                "Changes:   +{} -{} across {} hunk(s)",
                file.additions,
                file.deletions,
                file.hunks.len()
            ),
            format!("Language:  {lang}"),
        ];
        let (tl, tr, bl, br, hz, vt) = if ascii {
            ('+', '+', '+', '+', '-', '|')
        } else {
            ('┌', '┐', '└', '┘', '─', '│')
        };
        let top_title = " File Details ";
        let top_fill = hz
            .to_string()
            .repeat(card_w.saturating_sub(2 + top_title.len()));
        let top_border = format!("{tl}{top_title}{top_fill}{tr}");
        let bot_title = " y copy header   Esc / i close ";
        let bot_fill = hz
            .to_string()
            .repeat(card_w.saturating_sub(2 + bot_title.len()));
        let bot_border = format!("{bl}{bot_title}{bot_fill}{br}");

        let start_row = 3usize;
        write!(
            writer,
            "\x1b[{start_row};{start_col}H\x1b[7m\x1b[1m{top_border}\x1b[0m"
        )?;
        for (idx, line) in body_lines.iter().enumerate() {
            let r = start_row + 1 + idx;
            if r > visible_height {
                break;
            }
            let clipped = truncate_display_width(line, inner_w);
            let padded = tigrs_core::ansi::pad_display_width(clipped, inner_w);
            write!(
                writer,
                "\x1b[{r};{start_col}H\x1b[7m{vt} {padded} {vt}\x1b[0m"
            )?;
        }
        let bot_row = (start_row + 1 + body_lines.len()).min(visible_height + 1);
        write!(
            writer,
            "\x1b[{bot_row};{start_col}H\x1b[7m\x1b[1m{bot_border}\x1b[0m"
        )?;
        Ok(())
    }

    /// Renders the complete diff view to the terminal with options.
    pub fn render_with_options<W: Write>(
        &self,
        writer: &mut W,
        width: u16,
        height: u16,
        options: &ViewOptions,
    ) -> Result<()> {
        let caps = TerminalCapabilities::detect();
        self.render_with_capabilities(writer, width, height, options, &caps)
    }
}

impl super::View for DiffView {
    fn kind(&self) -> crate::app::layout::ViewKind {
        crate::app::layout::ViewKind::Diff
    }

    fn line_count(&self) -> usize {
        self.line_count()
    }

    fn nav(&self) -> &ViewportCursor {
        &self.nav
    }

    fn nav_mut(&mut self) -> &mut ViewportCursor {
        &mut self.nav
    }

    fn render(
        &self,
        mut writer: &mut dyn std::io::Write,
        width: u16,
        height: u16,
        options: &crate::options::ViewOptions,
    ) -> tigrs_core::error::Result<()> {
        self.render_with_options(&mut writer, width, height, options)
    }

    fn page_down(&mut self, visible_height: usize) {
        self.page_down(visible_height);
    }

    fn matches_search(&self, index: usize, pat: &crate::search::SearchPattern) -> bool {
        self.line_text(index).is_some_and(|text| pat.is_match(text))
    }

    fn page_up(&mut self, visible_height: usize) {
        self.page_up(visible_height);
    }

    fn scroll_left(&mut self, n: usize) {
        self.scroll_left(n);
    }

    fn scroll_right(&mut self, n: usize) {
        self.scroll_right(n);
    }

    fn scroll_first_col(&mut self) {
        self.scroll_first_col();
    }

    fn populate_macro_context(&self, ctx: &mut tigrs_core::macro_ctx::MacroContext) {
        if let Some(path) = self.current_file() {
            ctx.file = Some(path.to_string());
        }
        if let Some((_, _, line_idx)) = self.selected_line() {
            ctx.lineno = Some(line_idx + 1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use tigrs_git::{
        DiffHunk, DiffLineKind, DiffSummaryStats, FileChangeStatus, FileDiff, HunkLine, ObjectId,
    };

    fn make_test_diff() -> CommitDiff {
        let sha1 = ObjectId::empty_tree(gix::hash::Kind::Sha1);
        CommitDiff {
            commit_id: sha1,
            parent_ids: vec![],
            author_name: Arc::from("Alice"),
            author_email: Arc::from("alice@example.com"),
            author_date: "Mon Sep 1 12:00:00 2026 +0000".to_string(),
            committer_name: Arc::from("Alice"),
            committer_email: Arc::from("alice@example.com"),
            committer_date: "Mon Sep 1 12:00:00 2026 +0000".to_string(),
            title: Arc::from("Add important feature"),
            body: Some("Detailed notes on the feature.\nSecond line.".to_string()),
            files: vec![
                FileDiff {
                    path: "src/main.rs".to_string(),
                    status: FileChangeStatus::Modified,
                    old_id: Some(sha1),
                    new_id: Some(sha1),
                    old_mode: Some(0o100_644),
                    new_mode: Some(0o100_644),
                    is_binary: false,
                    additions: 2,
                    deletions: 1,
                    hunks: vec![DiffHunk {
                        old_start: 1,
                        old_len: 3,
                        new_start: 1,
                        new_len: 4,
                        func_context: None,
                        lines: vec![
                            HunkLine {
                                kind: DiffLineKind::Context,
                                content: "fn main() {".to_string(),
                                no_newline_at_eof: false,
                            },
                            HunkLine {
                                kind: DiffLineKind::Remove,
                                content: "    old_code();".to_string(),
                                no_newline_at_eof: false,
                            },
                            HunkLine {
                                kind: DiffLineKind::Add,
                                content: "    new_code();".to_string(),
                                no_newline_at_eof: false,
                            },
                            HunkLine {
                                kind: DiffLineKind::Add,
                                content: "    more_code();".to_string(),
                                no_newline_at_eof: false,
                            },
                            HunkLine {
                                kind: DiffLineKind::Context,
                                content: "}".to_string(),
                                no_newline_at_eof: false,
                            },
                        ],
                    }],
                },
                FileDiff {
                    path: "README.md".to_string(),
                    status: FileChangeStatus::Added,
                    old_id: None,
                    new_id: Some(sha1),
                    old_mode: None,
                    new_mode: Some(0o100_644),
                    is_binary: false,

                    additions: 1,
                    deletions: 0,
                    hunks: vec![DiffHunk {
                        old_start: 0,
                        old_len: 0,
                        new_start: 1,
                        new_len: 1,
                        func_context: None,
                        lines: vec![HunkLine {
                            kind: DiffLineKind::Add,
                            content: "# Readme".to_string(),
                            no_newline_at_eof: false,
                        }],
                    }],
                },
            ],
            stats: DiffSummaryStats {
                files_changed: 2,
                insertions: 3,
                deletions: 1,
            },
        }
    }

    #[test]
    fn test_diff_view_initialization_and_navigation() {
        let diff = make_test_diff();
        let mut view = DiffView::new(diff);

        assert!(view.line_count() > 20);
        assert_eq!(view.cursor_index(), 0);

        // Move down and up
        view.move_down(5, 15);
        assert_eq!(view.cursor_index(), 5);

        view.move_up(2, 15);
        assert_eq!(view.cursor_index(), 3);

        // Next hunk jump
        view.next_hunk(15);
        assert!(view.cursor_index() > 3);
        let hunk_row = &view.document.rows[view.cursor_index()];
        assert_eq!(hunk_row.row_type, DiffLineType::HunkHeader);
        assert!(
            hunk_row.search_text().contains("unchanged lines")
                || hunk_row.search_text().contains("lines ")
                || hunk_row.search_text().starts_with("@@")
        );
        // Copy fidelity ('y') on a Banner hunk header returns the real @@ header
        assert!(view.yank_text_at_cursor().unwrap().starts_with("@@"));

        // Next hunk jump again (to README hunk)
        view.next_hunk(15);
        let second_hunk = &view.document.rows[view.cursor_index()];
        assert_eq!(second_hunk.row_type, DiffLineType::HunkHeader);
        assert_eq!(view.current_file(), Some("README.md"));

        // Prev hunk jump
        view.prev_hunk(15);
        assert_eq!(view.current_file(), Some("src/main.rs"));

        // Home and End
        view.home();
        assert_eq!(view.cursor_index(), 0);

        view.end(15);
        assert_eq!(view.cursor_index(), view.line_count() - 1);
    }

    #[test]
    fn test_diff_view_file_jumps() {
        let diff = make_test_diff();
        let mut view = DiffView::new(diff);

        // Jump to first file
        view.next_file(20);
        let f1 = &view.document.rows[view.cursor_index()];
        assert_eq!(f1.row_type, DiffLineType::FileHeader);
        assert!(f1.search_text().contains("src/main.rs"));
        assert_eq!(view.current_file(), Some("src/main.rs"));

        // Jump to second file
        view.next_file(20);
        let f2 = &view.document.rows[view.cursor_index()];
        assert_eq!(f2.row_type, DiffLineType::FileHeader);
        assert!(f2.search_text().contains("README.md"));
        assert_eq!(view.current_file(), Some("README.md"));

        // Jump back to first file
        view.prev_file(20);
        assert_eq!(view.current_file(), Some("src/main.rs"));
    }

    #[test]
    fn test_diff_view_render_to_buffer() {
        let diff = make_test_diff();
        let view = DiffView::new(diff);

        let mut buffer = Vec::new();
        view.render(&mut buffer, 80, 24).expect("render succeeds");

        let rendered = String::from_utf8_lossy(&buffer);
        assert!(rendered.contains("[diff]"));
        assert!(rendered.contains("Add important feature"));
        assert!(rendered.contains("src/main.rs"));
        assert!(rendered.contains("line 1 of"));
    }

    #[test]
    fn test_diff_view_selected_hunk_and_line() {
        let diff = make_test_diff();
        let mut view = DiffView::new(diff);

        // Line 0 is commit header; no hunk
        assert!(view.selected_hunk().is_none());
        assert!(view.selected_line().is_none());

        // Jump to first hunk header
        view.next_hunk(20);
        let hunk_res = view.selected_hunk();
        assert!(hunk_res.is_some());
        let (file, hunk) = hunk_res.unwrap();
        assert_eq!(file.path, "src/main.rs");
        assert_eq!(hunk.old_start, 1);
        // On hunk header itself, selected_line is None
        assert!(view.selected_line().is_none());

        // Move down by 1 line into first content line (context: fn main() {)
        view.move_down(1, 20);
        let line_res = view.selected_line();
        assert!(line_res.is_some());
        let (f, h, l_idx) = line_res.unwrap();
        assert_eq!(f.path, "src/main.rs");
        assert_eq!(h.old_start, 1);
        assert_eq!(l_idx, 0);
        assert_eq!(h.lines[l_idx].kind, DiffLineKind::Context);

        // Move down to next line (deletion)
        view.move_down(1, 20);
        let line_res = view.selected_line().unwrap();
        assert_eq!(line_res.2, 1);
        assert_eq!(line_res.1.lines[1].kind, DiffLineKind::Remove);
    }

    #[test]
    fn test_diff_view_status_item_rendering() {
        let diff = make_test_diff();
        let item = StatusItem::new('M', StatusSection::Unstaged, "src/main.rs", None);
        let view = DiffView::new_status(diff, item);
        assert!(view.status_item().is_some());
        assert_eq!(view.status_item().unwrap().path, "src/main.rs");

        let mut buffer = Vec::new();
        view.render(&mut buffer, 100, 24).expect("render succeeds");
        let rendered = String::from_utf8_lossy(&buffer);
        assert!(rendered.contains("[status-diff]"));
        assert!(rendered.contains("u: stage hunk"));
    }

    // --- Word-level (intra-line) diff emphasis ---

    fn hunk_line(kind: DiffLineKind, content: &str) -> HunkLine {
        HunkLine {
            kind,
            content: content.to_string(),
            no_newline_at_eof: false,
        }
    }

    /// Builds a one-file, one-hunk diff from the given hunk lines.
    fn diff_with_lines(hunk_lines: Vec<HunkLine>) -> CommitDiff {
        let sha1 = ObjectId::empty_tree(gix::hash::Kind::Sha1);
        CommitDiff {
            commit_id: sha1,
            parent_ids: vec![],
            author_name: Arc::from("Alice"),
            author_email: Arc::from("alice@example.com"),
            author_date: "Mon Sep 1 12:00:00 2026 +0000".to_string(),
            committer_name: Arc::from("Alice"),
            committer_email: Arc::from("alice@example.com"),
            committer_date: "Mon Sep 1 12:00:00 2026 +0000".to_string(),
            title: Arc::from("Change"),
            body: None,
            files: vec![FileDiff {
                path: "src/lib.rs".to_string(),
                status: FileChangeStatus::Modified,
                old_id: Some(sha1),
                new_id: Some(sha1),
                old_mode: Some(0o100_644),
                new_mode: Some(0o100_644),
                is_binary: false,
                additions: 1,
                deletions: 1,
                hunks: vec![DiffHunk {
                    old_start: 1,
                    old_len: 1,
                    new_start: 1,
                    new_len: 1,
                    func_context: None,
                    lines: hunk_lines,
                }],
            }],
            stats: DiffSummaryStats::default(),
        }
    }

    /// Extracts the emphasised substrings of the first line of the given kind
    /// whose text contains `needle`.
    ///
    /// Matching is by `DiffLineType` rather than by leading character because
    /// the `---` / `+++` file headers also begin with `-` and `+`.
    fn emphasised_text(view: &DiffView, kind: DiffLineType, needle: &str) -> Vec<String> {
        let row = view
            .document
            .rows
            .iter()
            .find(|r| r.row_type == kind && r.search_text().contains(needle))
            .expect("line present");
        let cell = row.left.as_ref().unwrap();
        let chars: Vec<char> = cell.text.chars().collect();
        cell.emphasis
            .iter()
            .map(|&(s, e)| chars[s as usize..e as usize].iter().collect())
            .collect()
    }

    #[test]
    fn test_word_diff_marks_only_changed_token_in_pair() {
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Context, "fn main() {"),
            hunk_line(DiffLineKind::Remove, "    let total = compute_total(a, b);"),
            hunk_line(DiffLineKind::Add, "    let total = compute_sum(a, b);"),
        ]);
        let view = DiffView::new(diff);

        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffDel, "let total"),
            vec!["compute_total"]
        );
        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffAdd, "let total"),
            vec!["compute_sum"]
        );
    }

    #[test]
    fn test_word_diff_offsets_account_for_diff_prefix() {
        // Word diffing is token-based and suppresses pairs where *both* sides
        // are almost entirely rewritten, so the fixture has to keep most of the
        // line intact for any emphasis to survive.
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let x = 1;"),
            hunk_line(DiffLineKind::Add, "let x = 2;"),
        ]);
        let view = DiffView::new(diff);

        let del_row = view
            .document
            .rows
            .iter()
            .find(|r| r.row_type == DiffLineType::DiffDel)
            .expect("del line");
        let del = del_row.left.as_ref().unwrap();
        // In cell.text ("let x = 1;"), token '1' is at 8..9.
        // In search_text ("-let x = 1;"), token '1' is at 9..10.
        assert_eq!(del.emphasis, vec![(8, 9)]);
        assert_eq!(&del.text[8..9], "1");
        assert_eq!(&del_row.search_text()[9..10], "1");
    }

    #[test]
    fn test_word_diff_skips_unequal_length_runs() {
        // 1 removed, 2 added: no reliable pairing, so no emphasis at all.
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let a = 1;"),
            hunk_line(DiffLineKind::Add, "let a = 1;"),
            hunk_line(DiffLineKind::Add, "let b = 2;"),
        ]);
        let view = DiffView::new(diff);

        for row in &view.document.rows {
            if let Some(cell) = &row.left {
                assert!(
                    cell.emphasis.is_empty(),
                    "unequal runs must not be paired: {cell:?}"
                );
            }
        }
    }

    #[test]
    fn test_word_diff_skips_pure_additions() {
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Context, "fn main() {"),
            hunk_line(DiffLineKind::Add, "    println!(\"hi\");"),
        ]);
        let view = DiffView::new(diff);

        for row in &view.document.rows {
            if let Some(cell) = &row.left {
                assert!(cell.emphasis.is_empty());
            }
        }
    }

    #[test]
    fn test_word_diff_pairs_equal_length_runs_positionally() {
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let x = 1;"),
            hunk_line(DiffLineKind::Remove, "let y = 2;"),
            hunk_line(DiffLineKind::Add, "let x = 10;"),
            hunk_line(DiffLineKind::Add, "let y = 20;"),
        ]);
        let view = DiffView::new(diff);

        // Each removed line pairs with the added line at the same offset.
        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffDel, "let x"),
            vec!["1"]
        );
        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffAdd, "let x"),
            vec!["10"]
        );
        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffDel, "let y"),
            vec!["2"]
        );
        assert_eq!(
            emphasised_text(&view, DiffLineType::DiffAdd, "let y"),
            vec!["20"]
        );
    }

    #[test]
    fn test_word_diff_rendering_emits_emphasis_escapes() {
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let total = old_name(a);"),
            hunk_line(DiffLineKind::Add, "let total = new_name(a);"),
        ]);
        let view = DiffView::new(diff);

        let opts = crate::options::ViewOptions {
            word_diff: true,
            ..Default::default()
        };
        let mut buffer = Vec::new();
        view.render_with_options(&mut buffer, 100, 24, &opts)
            .expect("render succeeds");
        let rendered = String::from_utf8_lossy(&buffer);

        assert!(
            rendered.contains("48;5;22m"),
            "added line should carry the add emphasis style"
        );
        assert!(
            rendered.contains("48;5;52m"),
            "removed line should carry the del emphasis style"
        );
    }

    #[test]
    fn test_word_diff_disabled_emits_no_emphasis_escapes() {
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let total = old_name(a);"),
            hunk_line(DiffLineKind::Add, "let total = new_name(a);"),
        ]);
        let view = DiffView::new(diff);

        let opts = crate::options::ViewOptions {
            word_diff: false,
            ..Default::default()
        };
        let mut buffer = Vec::new();
        view.render_with_options(&mut buffer, 100, 24, &opts)
            .expect("render succeeds");
        let rendered = String::from_utf8_lossy(&buffer);

        assert!(!rendered.contains("48;5;22m"));
        assert!(!rendered.contains("48;5;52m"));

        for profile in [
            crate::term_cap::ColorProfile::Monochrome,
            crate::term_cap::ColorProfile::Ansi16,
            crate::term_cap::ColorProfile::Ansi256,
            crate::term_cap::ColorProfile::TrueColor,
        ] {
            let caps = crate::term_cap::TerminalCapabilities {
                color_profile: profile,
                supports_kitty_keyboard: false,
                supports_unicode_box: true,
                supports_synchronized_output: false,
            };
            let mut cap_buf = Vec::new();
            view.render_with_capabilities(&mut cap_buf, 100, 24, &opts, &caps)
                .expect("render with caps succeeds");
            let cap_rendered = String::from_utf8_lossy(&cap_buf);
            assert!(
                !cap_rendered.contains("48;5;22m"),
                "Unexpected add emphasis escape under {profile:?}"
            );
            assert!(
                !cap_rendered.contains("48;5;52m"),
                "Unexpected del emphasis escape under {profile:?}"
            );
        }
    }

    #[test]
    fn test_word_diff_rendered_text_is_unchanged_by_emphasis() {
        // Emphasis must only add escape sequences; the visible characters of
        // the row must be byte-identical with the feature on and off.
        let diff = diff_with_lines(vec![
            hunk_line(DiffLineKind::Remove, "let total = old_name(a);"),
            hunk_line(DiffLineKind::Add, "let total = new_name(a);"),
        ]);
        let view = DiffView::new(diff);

        let strip = |word_diff: bool| {
            let opts = crate::options::ViewOptions {
                word_diff,
                ..Default::default()
            };
            let mut buffer = Vec::new();
            view.render_with_options(&mut buffer, 100, 24, &opts)
                .expect("render succeeds");
            let text = String::from_utf8_lossy(&buffer).into_owned();
            // Drop every escape sequence, keeping only printable payload.
            let mut out = String::new();
            let mut chars = text.chars();
            while let Some(c) = chars.next() {
                if c == '\x1b' {
                    for t in chars.by_ref() {
                        if t.is_ascii_alphabetic() {
                            break;
                        }
                    }
                } else {
                    out.push(c);
                }
            }
            out
        };

        assert_eq!(strip(true), strip(false));
    }

    #[test]
    fn test_diff_view_additional_coverage() {
        let sha1 = ObjectId::from_hex(b"1111111111111111111111111111111111111111").unwrap();
        let sha2 = ObjectId::from_hex(b"2222222222222222222222222222222222222222").unwrap();

        // 1. Merge commit with 0 files changed
        let empty_merge_diff = CommitDiff {
            commit_id: sha1,
            parent_ids: vec![sha1, sha2],
            author_name: Arc::from("Author"),
            author_email: Arc::from("a@example.com"),
            author_date: "date".to_string(),
            committer_name: Arc::from("Author"),
            committer_email: Arc::from("a@example.com"),
            committer_date: "date".to_string(),
            title: Arc::from("Merge branch 'feature'"),
            body: None,
            files: vec![],
            stats: DiffSummaryStats {
                files_changed: 0,
                insertions: 0,
                deletions: 0,
            },
        };
        let empty_view = DiffView::new(empty_merge_diff);
        let mut buf = Vec::new();
        empty_view.render(&mut buf, 80, 24).unwrap();
        let rendered = String::from_utf8_lossy(&buf);
        assert!(rendered.contains("Merge: 1111111 2222222"));
        assert!(rendered.contains("0 files changed"));

        // 2. Diff with Rename, Copy, Deleted with mode, and Binary file
        let complex_diff = CommitDiff {
            commit_id: sha1,
            parent_ids: vec![sha2],
            author_name: Arc::from("Author"),
            author_email: Arc::from("a@example.com"),
            author_date: "date".to_string(),
            committer_name: Arc::from("Author"),
            committer_email: Arc::from("a@example.com"),
            committer_date: "date".to_string(),
            title: Arc::from("Complex changes"),
            body: None,
            files: vec![
                FileDiff {
                    path: "renamed_dest.rs".to_string(),
                    status: FileChangeStatus::Renamed {
                        source_path: "renamed_src.rs".to_string(),
                        similarity_pct: 95,
                    },
                    old_id: Some(sha1),
                    new_id: Some(sha2),
                    old_mode: Some(0o100_644),
                    new_mode: Some(0o100_644),
                    is_binary: false,
                    additions: 1,
                    deletions: 0,
                    hunks: vec![DiffHunk {
                        old_start: 1,
                        old_len: 1,
                        new_start: 1,
                        new_len: 2,
                        func_context: None,
                        lines: vec![
                            HunkLine {
                                kind: DiffLineKind::Context,
                                content: "common".to_string(),
                                no_newline_at_eof: false,
                            },
                            HunkLine {
                                kind: DiffLineKind::Add,
                                content: "added".to_string(),
                                no_newline_at_eof: false,
                            },
                        ],
                    }],
                },
                FileDiff {
                    path: "copied_dest.rs".to_string(),
                    status: FileChangeStatus::Copied {
                        source_path: "copied_src.rs".to_string(),
                        similarity_pct: 90,
                    },
                    old_id: Some(sha1),
                    new_id: Some(sha2),
                    old_mode: Some(0o100_644),
                    new_mode: Some(0o100_644),
                    is_binary: false,
                    additions: 0,
                    deletions: 0,
                    hunks: vec![],
                },
                FileDiff {
                    path: "deleted.rs".to_string(),
                    status: FileChangeStatus::Deleted,
                    old_id: Some(sha1),
                    new_id: None,
                    old_mode: Some(0o100_644),
                    new_mode: None,
                    is_binary: false,
                    additions: 0,
                    deletions: 1,
                    hunks: vec![],
                },
                FileDiff {
                    path: "image.png".to_string(),
                    status: FileChangeStatus::Modified,
                    old_id: Some(sha1),
                    new_id: Some(sha2),
                    old_mode: Some(0o100_644),
                    new_mode: Some(0o100_644),
                    is_binary: true,
                    additions: 0,
                    deletions: 0,
                    hunks: vec![],
                },
            ],
            stats: DiffSummaryStats {
                files_changed: 4,
                insertions: 1,
                deletions: 1,
            },
        };

        let mut complex_view = DiffView::new(complex_diff.clone());
        let opts = crate::options::ViewOptions {
            line_number: true,
            ..Default::default()
        };
        let mut complex_buf = Vec::new();
        complex_view
            .render_with_options(&mut complex_buf, 100, 100, &opts)
            .unwrap();
        let complex_rendered = String::from_utf8_lossy(&complex_buf);
        // Banner presentation: brace-diffed renames/copies, status chips, and (binary)
        assert!(complex_rendered.contains("R95"));
        assert!(complex_rendered.contains("renamed_{src → dest}.rs"));
        assert!(complex_rendered.contains("C90"));
        assert!(complex_rendered.contains("copied_{src → dest}.rs"));
        assert!(complex_rendered.contains("(binary)"));

        // Classic presentation: full multi-line git headers
        let classic_opts = crate::options::ViewOptions {
            line_number: true,
            diff_presentation: crate::options::DiffPresentation::Classic,
            ..Default::default()
        };
        let classic_view = DiffView::new_with_options(complex_diff, &classic_opts, None);
        let mut classic_buf = Vec::new();
        classic_view
            .render_with_options(&mut classic_buf, 100, 100, &classic_opts)
            .unwrap();
        let classic_rendered = String::from_utf8_lossy(&classic_buf);
        assert!(classic_rendered.contains("rename from renamed_src.rs"));
        assert!(classic_rendered.contains("rename to renamed_dest.rs"));
        assert!(classic_rendered.contains("copy from copied_src.rs"));
        assert!(classic_rendered.contains("copy to copied_dest.rs"));
        assert!(classic_rendered.contains("deleted file mode 100644"));
        assert!(classic_rendered.contains("Binary files differ"));

        // 3. Navigation: page_down, page_up, scroll_line_up
        complex_view.page_down(10);
        assert!(complex_view.cursor_index() > 0);
        complex_view.page_up(10);
        assert_eq!(complex_view.cursor_index(), 0);

        complex_view.scroll_line_down(5, 10);
        complex_view.scroll_line_up(5, 10);
        assert_eq!(complex_view.scroll_offset(), 0);

        // 4. Zero dimensions render
        let mut zero_buf = Vec::new();
        assert!(complex_view.render(&mut zero_buf, 0, 0).is_ok());
    }
}
